services:
  - type: web
    name: all1digitalz  # Change this to your actual app name
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
